apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs-executor
  {{ if .Values.agentNamespace }}
  namespace: {{ .Values.agentNamespace }}
  {{ end }}
rules:
  - apiGroups: [""]  # "" indicates the core API group
    resources: [services]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [batch]
    resources: [jobs]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]  # "" indicates the core API group
    resources: [pods]
    verbs: [list, get, delete, create]
  # this rule is required for sprint-cloud-kubernetes-fabric8-config
  - apiGroups: [""]  # "" indicates the core API group
    resources: [configmaps, secrets]
    verbs: [list, get, watch]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-jobs-binding
  {{ if .Values.agentNamespace }}
  namespace: {{ .Values.agentNamespace }}
  {{ end }}
subjects:
  - kind: ServiceAccount
    name: orchestrator-sa
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-executor

---

# Bind orchestrator-sa to ClusterRole required for TokenReview access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orchestrator-microservice-role-binding
subjects:
  - kind: ServiceAccount
    name: orchestrator-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microservice
