/**
 * The map of keys to descriptions of each field in COSV schema
 */

package com.saveourtool.save.frontend.components.views.vuln.utils

val cosvFieldsDescriptionsMap = listOf(
    "schema_version" to schemaVersionDescr,
    "id" to idDescr,
    "modified" to modifiedDescr,
    "published" to publishedDescr,
    "withdrawn" to withdrawnDescr,
    "aliases" to aliasesDescr,
    "cwe_ids" to cweIdsDescr,
    "cwe_names" to cweNamesDescr,
    "timeline" to timelineDescr,
    "timeline.type" to timelineTypeDescr,
    "timeline.value" to timelineValueDescr,
    "related" to relatedDescr,
    "summary" to summaryDescr,
    "details" to detailsDescr,
    "severity" to severityDescr,
    "severity.type" to severityTypeDescr,
    "severity.score" to severityScoreDescr,
    "severity.level" to severityLevelDescr,
    "severity.score_num" to severityScoreNumDescr,
    "affected" to affectedDescr,
    "package" to packageDescr,
    "ecosystem" to packageEcosystemDescr,
    "package.name" to packageNameDescr,
    "purl" to packagePurlDescr,
    "language" to packageLanguageDescr,
    "repository" to packageRepositoryDescr,
    "introduced_commits" to packageIntroducedCommitsDescr,
    "fixed_commits" to packageFixedCommitsDescr,
    "home_page" to packageHomePageDescr,
    "edition" to packageEditionDescr,
    "versions" to affectedVersionsDescr,
    "ranges" to rangesDescr,
    "ranges.type" to rangesTypeDescr,
    "ranges.repo" to rangesRepoDescr,
    "events" to rangesEventsDescr,
    "introduced" to eventsIntroducedDescr,
    "fixed" to eventsFixedDescr,
    "last_affected" to eventsLastAffectedDescr,
    "limit" to eventsLimitDescr,
    "ranges.database_specific" to rangesDatabaseSpecificDescr,
    "affected.ecosystem_specific" to affectedEcosystemSpecificDescr,
    "affected.database_specific" to affectedDatabaseSpecificDescr,
    "patches_detail" to patchesDetailDescr,
    "patch_url" to patchesPatchUrlDescr,
    "issue_url" to patchesIssueUrlDescr,
    "main_language" to patchesMainLanguageDescr,
    "author" to patchesAuthorDescr,
    "commiter" to patchesCommiterDescr,
    "branches" to patchesBranchesDescr,
    "tags" to patchesTagsDescr,
    "contributors" to contributorsDescr,
    "org" to contributorsOrgDescr,
    "contributors.name" to contributorsNameDescr,
    "email" to contributorsEmailDescr,
    "contributions" to contributionsDescr,
    "confirm_type" to confirmTypeDescr,
    "references" to referencesDescr,
    "references.type" to referencesTypeDescr,
    "url" to referencesUrlDescr,
    "credits" to creditsDescr,
    "credits.name" to creditsNameDescr,
    "contact" to creditsContactDescr,
    "credits.type" to creditsTypeDescr,
    "database_specific" to databaseSpecificDescr,
)
