apiVersion: v2
name: save-cloud
description: Helm chart for SAVE Cloud service
# todo: separate versioning of charts or aligned with project version?
version: 0.2.0
appVersion: "0.3.0-SNAPSHOT"
sources:
  - https://github.com/saveourtool/save-cloud
  - https://github.com/saveourtool/save-cli
dependencies:
  - name: grafana
    version: <=7.0.2
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: prometheus
    version: ^19.0.0 <=19.3.3
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: promtail
    version: ^6.0.0 <=6.8.2
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: loki
    version: ^4.0.0 <=4.4.2
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: neo4j
    version: ^5.0.0
    repository: https://helm.neo4j.com/neo4j
    condition: neo4j.enabled
