dependencies:
  - name: grafana
    version: ^5.0.0
    repository: https://grafana.github.io/helm-charts
  - name: prometheus
    version: ^15.8.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: promtail
    version: ^4.0.0
    repository: https://grafana.github.io/helm-charts
  - name: loki
    version: ^2.0.0
    repository: https://grafana.github.io/helm-charts
